sudo: required
dist: trusty
language:
  - java
jdk:
  - oraclejdk8  # Building Bazel requires JDK8.
before_script:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install bazel 0.3.1
script:
  - bazel build //...
  - bazel test //...
